### ISSUE TITLE
 CL100-WETH/USDC Contract not showing in my Dashboard

### ISSUE THREAD

**Issue by ngisvold** [velodrome-finance/slipstream#1]
Here is my contract: 0xc741beb2156827704A1466575ccA1cBf726a1178

It no longer shows in my dashboard after withdrawing emissions.

**Comment by ngisvold** [comment]
I actually have two contracts not showing: https://basescan.org/token/0xc741beb2156827704a1466575cca1cbf726a1178?a=0xa578994a409696e4d8d1cdcc93aba4c34022c93b These are on Aerodrome

**Comment by stas** [comment]
Hey @ngisvold 

I'm not sure what was going on, but we offer support for web app related questions on Discord.
Gonna close this and feel free to reach out there please.
