### ISSUE TITLE
QuoterMath.sol like Uniswap

### ISSUE THREAD

**Issue by 0xsinhvu** [velodrome-finance/slipstream#2]
I see an example to calculate `amountOut` from Uniswap by using library below:

https://github.com/Uniswap/view-quoter-v3/blob/master/contracts/libraries/QuoterMath.sol

Can you write this? Or what's the difference between us & Uniswap?

**Comment by stas** [comment]
Hey @johnny-vu 

We're only using the Mixed Quoter as we need support for multiple hops/non-cl pools:
https://github.com/velodrome-finance/slipstream/blob/main/contracts/periphery/lens/MixedRouteQuoterV1.sol

We've also have a bunch of helpers to work with quotes here:
https://github.com/velodrome-finance/slipstream/blob/main/contracts/periphery/SugarHelper.sol

Gonna close this, but would suggest reaching out on Discord for questions/support.
